// Generated from the consolidated Hamilton PM source in scripts/import-hamilton-pm.js.
export const HAMILTON_PM_PAGES = [
 {
  "button_color": "blue",
  "parent_id": "6a25d8f8b078be1725624434",
  "is_published": true,
  "linked_device_id": null,
  "description": null,
  "button_label": null,
  "title": "Clean The 96 Head",
  "sort_order": 7,
  "id": "6a25df392e34554e894a13a2",
  "created_date": "2026-06-07T21:14:33.634000",
  "updated_date": "2026-06-07T21:14:33.634000",
  "created_by_id": "69ef1fa9654f018cd70e4bc0",
  "created_by": "clalit.rl@gmail.com",
  "is_sample": false
 },
 {
  "button_color": "blue",
  "parent_id": "6a25d8f8b078be1725624434",
  "is_published": true,
  "linked_device_id": null,
  "description": null,
  "button_label": null,
  "title": "Verification",
  "sort_order": 11,
  "id": "6a25df29184900a4cd00dd61",
  "created_date": "2026-06-07T21:14:17.178000",
  "updated_date": "2026-06-07T21:14:17.178000",
  "created_by_id": "69ef1fa9654f018cd70e4bc0",
  "created_by": "clalit.rl@gmail.com",
  "is_sample": false
 },
 {
  "button_color": "blue",
  "parent_id": "6a25d8f8b078be1725624434",
  "is_published": true,
  "linked_device_id": null,
  "description": null,
  "button_label": null,
  "title": "Check HO",
  "sort_order": 10,
  "id": "6a25df1ea2906147cfaab374",
  "created_date": "2026-06-07T21:14:06.322000",
  "updated_date": "2026-06-07T21:14:06.322000",
  "created_by_id": "69ef1fa9654f018cd70e4bc0",
  "created_by": "clalit.rl@gmail.com",
  "is_sample": false
 },
 {
  "button_color": "blue",
  "parent_id": "6a25d8f8b078be1725624434",
  "is_published": true,
  "linked_device_id": null,
  "description": null,
  "button_label": null,
  "title": "Adjust HO",
  "sort_order": 9,
  "id": "6a25df1100a8c916eebb0f74",
  "created_date": "2026-06-07T21:13:53.529000",
  "updated_date": "2026-06-07T21:13:53.529000",
  "created_by_id": "69ef1fa9654f018cd70e4bc0",
  "created_by": "clalit.rl@gmail.com",
  "is_sample": false
 },
 {
  "button_color": "blue",
  "parent_id": "6a25d8f8b078be1725624434",
  "is_published": true,
  "linked_device_id": null,
  "description": null,
  "button_label": null,
  "title": "Part Replacement 96",
  "sort_order": 8,
  "id": "6a25defcf397d9dde91b1011",
  "created_date": "2026-06-07T21:13:32.019000",
  "updated_date": "2026-06-07T21:13:32.019000",
  "created_by_id": "69ef1fa9654f018cd70e4bc0",
  "created_by": "clalit.rl@gmail.com",
  "is_sample": false
 },
 {
  "button_color": "blue",
  "parent_id": "6a25d8f8b078be1725624434",
  "is_published": true,
  "linked_device_id": null,
  "description": null,
  "button_label": null,
  "title": "Check PIP",
  "sort_order": 6,
  "id": "6a25dee42222536f2791c342",
  "created_date": "2026-06-07T21:13:08.605000",
  "updated_date": "2026-06-07T21:13:08.605000",
  "created_by_id": "69ef1fa9654f018cd70e4bc0",
  "created_by": "clalit.rl@gmail.com",
  "is_sample": false
 },
 {
  "button_color": "blue",
  "parent_id": "6a25d8f8b078be1725624434",
  "is_published": true,
  "linked_device_id": null,
  "description": null,
  "button_label": null,
  "title": "Adjust PIP",
  "sort_order": 5,
  "id": "6a25decdd4a15a47493e0511",
  "created_date": "2026-06-07T21:12:45.112000",
  "updated_date": "2026-06-07T21:12:45.112000",
  "created_by_id": "69ef1fa9654f018cd70e4bc0",
  "created_by": "clalit.rl@gmail.com",
  "is_sample": false
 },
 {
  "button_color": "blue",
  "parent_id": "6a25d8f8b078be1725624434",
  "is_published": true,
  "linked_device_id": null,
  "description": null,
  "button_label": null,
  "title": "Adjust PIP Manual",
  "sort_order": 4,
  "id": "6a25deb8f544af39075dfe62",
  "created_date": "2026-06-07T21:12:24.640000",
  "updated_date": "2026-06-07T21:12:24.640000",
  "created_by_id": "69ef1fa9654f018cd70e4bc0",
  "created_by": "clalit.rl@gmail.com",
  "is_sample": false
 },
 {
  "button_color": "blue",
  "parent_id": "6a25d8f8b078be1725624434",
  "is_published": true,
  "linked_device_id": null,
  "description": "",
  "button_label": null,
  "title": "Adjust PIP Squeezer & Z",
  "sort_order": 3,
  "id": "6a25de8dddcb162a2d7226e1",
  "created_date": "2026-06-07T21:11:41.599000",
  "updated_date": "2026-06-07T21:44:31.396000",
  "created_by_id": "69ef1fa9654f018cd70e4bc0",
  "created_by": "clalit.rl@gmail.com",
  "is_sample": false
 },
 {
  "button_color": "blue",
  "parent_id": "6a25d8f8b078be1725624434",
  "is_published": true,
  "linked_device_id": null,
  "description": null,
  "button_label": null,
  "title": "גירוז של הרובוט",
  "sort_order": 2,
  "id": "6a25dd9f1c519fd9977205a0",
  "created_date": "2026-06-07T21:07:43.914000",
  "updated_date": "2026-06-07T21:07:43.914000",
  "created_by_id": "69ef1fa9654f018cd70e4bc0",
  "created_by": "clalit.rl@gmail.com",
  "is_sample": false
 },
 {
  "button_color": "blue",
  "parent_id": "6a25d8f8b078be1725624434",
  "is_published": true,
  "linked_device_id": null,
  "description": "",
  "button_label": null,
  "title": "PM only 8 Ch",
  "sort_order": 1,
  "id": "6a25db5cd8503f9ef726db4b",
  "created_date": "2026-06-07T20:58:04.950000",
  "updated_date": "2026-06-07T21:17:24.154000",
  "created_by_id": "69ef1fa9654f018cd70e4bc0",
  "created_by": "clalit.rl@gmail.com",
  "is_sample": false
 },
 {
  "button_color": "blue",
  "parent_id": null,
  "is_published": true,
  "linked_device_id": "69f094abec6af8abfca4aabd",
  "description": "מרכז PM עבור Hamilton NGS Star — כל מערך מרוכז בדף אחד.",
  "button_label": "PM",
  "title": "Hamilton NGS Star PM",
  "sort_order": 0,
  "id": "6a25d8f8b078be1725624434",
  "created_date": "2026-06-07T20:47:52.700000",
  "updated_date": "2026-06-07T20:59:06.868000",
  "created_by_id": "69ef1fa9654f018cd70e4bc0",
  "created_by": "clalit.rl@gmail.com",
  "is_sample": false
 }
];
export const HAMILTON_PM_BLOCKS = [
 {
  "id": "hamilton-pm-01",
  "page_id": "6a25d8f8b078be1725624434",
  "block_title": "מבוא והכנה ל־PM",
  "text": "<p>מדריך PM לרובוטריק MICROLAB® STAR של Hamilton.</p><p>יש לעבוד לפי הסדר, לתעד כל שלב בצילומי מסך ולשמור את התיעוד בתיקיית ה־PM של התאריך.</p><p>המערכים אוחדו מדפי Google Sites מפוצלים כדי שכל מערך יהיה מרוכז בדף אחד.</p>",
  "image_url": null,
  "image_width": 360,
  "image_rotation": 0,
  "sort_order": 0
 },
 {
  "id": "hamilton-pm-02",
  "page_id": "6a25db5cd8503f9ef726db4b",
  "block_title": "PM Star only 8 Ch",
  "text": "<p>שלבים ותמונות בביצוע ה־PM לרובוטריק.</p><p>לפתוח תיקייה עם התאריך של היום במיקום הנכון.</p><p>בדרך כלל כבר קיימת תיקייה עם היסטוריה של PM במחשב.</p><p>עם כל פלטת כיול מגיע קובץ ערכים; יש לעדכן אותו במחשב לפני תחילת הטיפול.</p><p>יש לפתוח קובץ Word בתיקיית ה־PM עם השלבים שבתמונה.</p><p>לפתוח את קיצור הדרך שבתמונה.</p>",
  "image_url": null,
  "image_width": 360,
  "image_rotation": 0,
  "sort_order": 0
 },
 {
  "id": "hamilton-pm-03",
  "page_id": "6a25dd9f1c519fd9977205a0",
  "block_title": "גירוז של הרובוט",
  "text": "<p>לבצע את פעולות הגירוז לפי הוראות היצרן ולתעד את הביצוע בקובץ ה־PM.</p><p>לפני תחילת העבודה לוודא שהרובוט במצב בטוח, כבוי במידת הצורך ושאין תנועה פעילה.</p>",
  "image_url": null,
  "image_width": 360,
  "image_rotation": 0,
  "sort_order": 0
 },
 {
  "id": "hamilton-pm-04",
  "page_id": "6a25de8dddcb162a2d7226e1",
  "block_title": "Adjust PIP Squeezer And Z",
  "text": "<p>מאפס את הלחץ הפנימי בערוץ.</p><p>בחלון שנפתח לבחור את האפשרות Adjust PIP Squeezer And Z.</p><p>במידה ואין קיצור דרך, יש ליצור את קיצור הדרך.</p><p>בטיפול יש לבחור את כל הערוצים ולכן נבחרת אפשרות 0, כפי שמופיע בתמונה.</p><p>יש לבחור את המיקום לביצוע החלפת החלקים; רצוי מיקום 25.</p><p>כאשר הרובוט מביא את הערוצים למיקום הנבחר, להתחיל באופן ידני אחד־אחד.</p><p>יש לפרק את הסטופ דיסק X8 בעדינות.</p><p>יש להרים את השרוול השחור בעדינות, כמו בתמונה.</p><p>לנקות היטב את ה־CLLD עם נייר שאינו משאיר סיבים ובאמצעות אלכוהול 70%.</p><p>לעבור על כל אחד ואחד מהערוצים.</p><p>לאחר הניקוי ללחוץ OK כדי לאפס את ה־CLLD.</p><p>יש להכין את החלקים החדשים: סטופ דיסק, אטם ושייבה.</p><p>להוסיף נגיעה של לוקטייט ולסגור בכוח יד.</p><p>חובה לבדוק שהשייבה עלתה עד למעלה.</p><p>לאחר מכן לנקות שוב עם אלכוהול 70% משומן, לוקטייט ושאר לכלוכים.</p><p>לנקות אחד־אחד וללחוץ OK; יש המתנה של כ־20 דקות.</p><p>ללחוץ YES ולהניח את ה־JIG בשורה 25.</p><p>כאשר המערכת מבקשת להוציא את ה־JIG, אין צורך להוציא אותו; להשאיר אותו בשורה 25.</p><p>במידה שהבדיקה לא עברה, לחזור ולתקן בתוכנה.</p><p>לפרק את הסטופ דיסק, לנקות ולהריץ שוב רק את הערוץ שנכשל.</p><p>במידה שהבדיקה עברה, לצלם מסך ולהדביק לקובץ Word.</p><p>ללחוץ OK ולסגור את המקרו.</p>",
  "image_url": "/images/guides/5668a6172_WhatsAppImage2026-06-02at212906.jpeg",
  "image_width": 360,
  "image_rotation": 0,
  "sort_order": 0
 },
 {
  "id": "hamilton-pm-05",
  "page_id": "6a25deb8f544af39075dfe62",
  "block_title": "Adjust PIP Manual",
  "text": "<p>כיוון מכני של הערוץ.</p><p>לפתוח את המקרו.</p><p>כאשר המכשיר שואל האם לבצע Default, ללחוץ YES.</p><p>להעביר את ה־JIG לערוץ 50.</p><p>החלון מציג את שמונת הערוצים.</p><p>לבדוק אילו ערוצים לא עברו ולהכניס ערוץ־ערוץ בחלון הבא.</p><p>להתחיל מהערוץ בעל הסטייה הגבוהה ביותר.</p><p>המערכת תביא את הרובוט לצד ימין.</p><p>לפרק את הדלת השקופה בצד ימין.</p><p>לפתוח מעט ובעדינות את הברגים ולהזיז את הערוץ בהתאם להנחיה שבתמונה.</p><p>CW = עם כיוון השעון; CCW = נגד כיוון השעון.</p><p>בסיום הכיול המכני להוציא את הכלים ולבדוק שוב.</p><p>לחזור על התהליך עד לקבלת PASS.</p><p>לצלם את האישור שהכול תקין ולהדביק בסדר הנכון בקובץ Word.</p><p>ללחוץ NO ולצאת מהמקרו.</p>",
  "image_url": null,
  "image_width": 360,
  "image_rotation": 0,
  "sort_order": 0
 },
 {
  "id": "hamilton-pm-06",
  "page_id": "6a25decdd4a15a47493e0511",
  "block_title": "Adjust PIP",
  "text": "<p>לפתוח את המקרו.</p><p>ללחוץ YES רק במידה והוחלף ערוץ.</p><p>ללחוץ פעמיים ולאחר מכן ללחוץ YES.</p><p>רצוי לבדוק מיקום אפשרי לפני האישור; לבחור את המיקום הכי שמאלי.</p><p>יש לבחור מיקום לפני האישור; לבחור את המיקום הכי ימני.</p><p>להניח את ה־JIG בתוכנה שבחרת, בדוגמה מיקום 46.</p><p>להעביר את ה־JIG לתחנה המתאימה.</p><p>לצלם ולהדביק את התוצאה בקובץ Word.</p><p>לסיים את המקרו.</p>",
  "image_url": null,
  "image_width": 360,
  "image_rotation": 0,
  "sort_order": 0
 },
 {
  "id": "hamilton-pm-07",
  "page_id": "6a25dee42222536f2791c342",
  "block_title": "Check PIP",
  "text": "<p>לפתוח את המקרו.</p><p>לבחור את התחנה ולהעמיד את ה־JIG במיקום שנבחר; רצוי הכי שמאלה.</p><p>לבחור את המיקום הכי ימני ולהעביר את ה־JIG.</p><p>לצלם את הדוח ולהדביק אותו בקובץ Word.</p><p>לסיים את המקרו.</p>",
  "image_url": null,
  "image_width": 360,
  "image_rotation": 0,
  "sort_order": 0
 },
 {
  "id": "hamilton-pm-08",
  "page_id": "6a25df392e34554e894a13a2",
  "block_title": "Clean The 96 Head",
  "text": "<p>לכבות את הרובוט.</p><p>להזיז את הרובוט ימינה.</p><p>עם נייר מגבת ללא סיבים ואלכוהול 70% לנקות היטב את הראש.</p><p>עם מברשת ואלכוהול לנקות את שתי הערבות.</p><p>לוודא שלא נשארו לכלוך או שאריות נייר.</p>",
  "image_url": null,
  "image_width": 360,
  "image_rotation": 0,
  "sort_order": 0
 },
 {
  "id": "hamilton-pm-09",
  "page_id": "6a25defcf397d9dde91b1011",
  "block_title": "Part Replacement 96",
  "text": "<p>לכבות את הרובוט.</p><p>לפרק את הכיסוי השמאלי ולהזיז את הרובוט הכי שמאלה שאפשר.</p><p>זהירות: ה־CLLD רגיש מאוד; אין לפרק את הצינורית מעל ה־CLLD.</p><p>לפרק בזהירות את הסטופ דיסק.</p><p>ה־CLLD חייב לשבת בשגם.</p><p>יש להשתמש בסטופ דיסק, אטם ודיסקית.</p><p>יש לגעת עם ארגו (לוקטייט) רק בחלקים שמורכבים עם ה־CLLD.</p><p>להרכיב בעדינות ולא לסגור עד הסוף; יש להשתמש בטורק.</p><p>רק את ארבעת הברגים של ה־CLLD לסגור בטורק 10; זהירות, לא יותר.</p><p>להכין את הצינוריות: 96 פחות 4 = 92 צינוריות ללא ה־CLLD.</p><p>הפס צריך להיות כלפי מטה בהכנה.</p><p>את שאר הסטופ דיסק לסגור בטורק 60.</p>",
  "image_url": null,
  "image_width": 360,
  "image_rotation": 0,
  "sort_order": 0
 },
 {
  "id": "hamilton-pm-10",
  "page_id": "6a25df1100a8c916eebb0f74",
  "block_title": "Adjust HO",
  "text": "<p>להדליק את הרובוט.</p><p>לבחור את המקרו Adjust HO וללחוץ התחל.</p><p>להכניס את פרטי הראש 96.</p><p>להניח את ה־JIG בעמדה שנבחרה; עדיף עמדה 29, וללחוץ OK.</p><p>הראש 96 יגיע למיקום.</p><p>להוציא את ה־JIG האדום ולהרכיב אותו על הראש.</p><p>A1 חייב לשבת במיקום הנכון.</p><p>לבדוק שה־JIG יושב כראוי ומוצמד בכל הפינות.</p><p>הרובוט יבקש לפרק את ה־JIG האדום; להחזיק את ה־JIG בעדינות עד שהראש משחרר.</p><p>חובה להוציא את ה־JIG מעמדה 29.</p><p>לצלם את סיום המקרו, להדביק ל־Word, לשמור ולסגור אותו.</p>",
  "image_url": null,
  "image_width": 360,
  "image_rotation": 0,
  "sort_order": 0
 },
 {
  "id": "hamilton-pm-11",
  "page_id": "6a25df1ea2906147cfaab374",
  "block_title": "Check HO",
  "text": "<p>להפעיל את המקרו Check HO וללחוץ התחל.</p><p>להכניס את הקרייר; מומלץ לעמדה 25, כאשר הצד השמאלי של הקרייר נמצא על 25.</p><p>חובה לדעת את סוג הטיפים (גודל) לפני שממשיכים במקרו.</p><p>לבחור את העמדה שבה הקרייר נמצא וללחוץ OK.</p><p>לבחור את גודל הטיפ; מתחילים מעמדה 1, הפנימית ביותר, וחוזרים על השלב חמש פעמים:</p><p>1. רגיל.</p><p>2. כמות נוזל נמוכה — טיפ קטן 10.</p><p>3. כמות גדולה — טיפ גדול 1000.</p><p>לבדוק שהראש מרים ומוריד באופן מושלם את כל הטיפים (96 טיפים בכל פעם).</p><p>לצלם את הודעת הסיום, להדביק בקובץ Word ולסיים את המקרו.</p>",
  "image_url": null,
  "image_width": 360,
  "image_rotation": 0,
  "sort_order": 0
 },
 {
  "id": "hamilton-pm-12",
  "page_id": "6a25df29184900a4cd00dd61",
  "block_title": "Verification",
  "text": "<p>שלב זה מכין את הרובוט לפני ביצוע Verification.</p><p>הכי חשוב: לא לחבר את השנאים הפוך.</p><p>המשקל מתחבר לשנאי של המשקל; קורא הפלטות מתחבר לשנאי של קורא הפלטות.</p><p>להניח את ה־JIG בעמדה 25–24, כמו בתמונה.</p><p>בזהירות רבה להניח את המשקל במיקום ולחבר אותו.</p><p>להעביר את הכבל כך שלא יפריע לאוטו לודר לעבור.</p><p>להרכיב את ה־JIG השני מעל ולהרכיב את JIG המשקל.</p><p>כיוון הפין חייב להיות בצד ימין; לאחר ההרכבה לבדוק שה־JIG אינו מסתובב.</p><p>להרכיב את ה־JIG הנוסף כאשר השגם כלפי מטה ולהניח את הכלוב בעדינות מעל.</p><p>להניח את המיכלים הפלסטיים הקטנים במיקומים לפי התמונה.</p><p>להכין את ה־JIG הרביעי לפי התמונה, לשים לב למיקומי ארבעת הפינים ולכיוון ה־JIG.</p><p>לחבר את ה־JIG לרובוט בצמוד למשקל; הלודר מכניס אותו לתוך הרובוט. המיקום נקבע לפי צד שמאל.</p><p>להרכיב את ה־JIG של קורא הברקוד לרובוט.</p><p>לעמוד עם העכבר על האייקון, לבחור Maintenance and Verification ולאחר מכן Verification.</p><p>ללחוץ RUN.</p><p>לבחור את סוגי ה־Verification שרוצים לבצע, ולהכניס את שם הטכנאי, מיקום הרובוט, טמפרטורה ולחות.</p><p>לבדוק את הטמפרטורה והלחות עם החיישן שבארגז הכיול.</p><p>להכניס את המידע לפי מדבקות הכיול.</p><p>לעדכן את המידע של הפלטה האופטית, ללחוץ על הכפתור המתאים ולבחור את הקובץ מהתיקייה במחשב.</p><p>אפשר להמשיך רק כאשר כל המסך אפור.</p><p>לבחור את מיקום המשקל — הוא היחיד בצד ימין — ולוודא שקורא הפלטות מחובר.</p><p>כאשר ה־reader נפתח, עם כפפות להוציא את הפלטה מהקופסה ולהכניס אותה ל־reader.</p><p>לוודא שבפינה הימנית העליונה מופיע הסימון A1, ללחוץ OK ולהמתין לסיום הכיול.</p><p>להוציא את תא הפלטה של הכיול האופטי מה־Reader.</p><p>בדיקת קורא ברקוד: להעמיד את ה־JIG בעמדה בחוץ ולבחור את הערוץ הנכון, רצוי ערוץ 35.</p><p>לבדוק שהברקוד תקין, לשמור את הדוח בתיקיית PM, לבחור את הערוץ השמאלי של ה־JIG וללחוץ OK.</p><p>לבדוק את הדוח ולשמור אותו בתיקיית PM.</p><p>להוציא שלושה טיפים מברזל מתוך ארבעה ולהשאיר רק את הטיפ בפינה השמאלית העליונה.</p><p>להשאיר את המיקום וללחוץ OK; לוודא שהטיפ נמצא מעל ה־JIG במרכז וללחוץ OK.</p><p>בסיום הרובוט מוציא את ה־JIG והדוח; לבדוק ולשמור את הדוח בתיקיית PM.</p><p>לפתוח את קופסת המשקולת מהצד הנכון. אסור להפיל את המשקולת או לגעת בה, גם עם כפפות.</p><p>להוריד את הכלוב ולהניח את המשקולת בעדינות בעזרת פינצטה, לסגור את הכלוב ולהחזיר את המשקולת מיד לקופסה.</p><p>למלא את הנוזלים לפי התמונה וללחוץ OK.</p><p>להכניס את המידע לפי הקופסה, עם הלוט והתאריך הנכונים, וללחוץ OK.</p><p>להסיר את הכלוב ואת שאר ה־JIG ולהרכיב את מתקן הפלטות.</p><p>לוודא ש־A1 בפינה השמאלית העליונה, להעמיד את המתקנים ולמלא נוזלים לפי התמונה.</p><p>ב־JIG הימני להכניס טיפים בגודל 1000 כאשר הברקוד בצד ימין, במיקום 1.</p><p>ב־JIG הימני להכניס טיפים בגודל 10 כאשר הברקוד בצד ימין, במיקום 2.</p><p>להרכיב שלוש פלטות במיקומים 3, 4 ו־5, לבחור את המיקום הימני וללחוץ OK.</p><p>לוודא שהטיפים עומדים ישר מעל הפלטה; אם לא, ליישר את הפלטה בעדינות.</p><p>כאשר המערכת מבקשת, להעביר בעדינות את הפלטה מהמשקל אל הקורא ולוודא A1 במיקום הנכון.</p><p>בהתאם להוראת המערכת להכניס בכל פעם פלטה אחרת לקורא; אין צורך להוציא את ה־JIG מהמכשיר.</p><p>לוודא שהכול עבר בדוח ולשמור את הדוח בתיקיית PM.</p><p>להוציא את ה־JIG מהמשקל וללחוץ OK.</p><p>להכניס את הלוט של הנוזלים ולהוסיף פלטה למשקל ונוזלים במידת הצורך.</p><p>לוודא A1 במיקום הנכון, כיוון הברקוד של טיפים 1000 בעמדה 1 ושל טיפים 10 בעמדה 2, ופלטות בעמדות 3 ו־4.</p><p>ללחוץ OK ולהשלים את סדרת הבדיקות עבור המשקל ופלטות 3, 4 ו־5.</p>",
  "image_url": null,
  "image_width": 360,
  "image_rotation": 0,
  "sort_order": 0
 }
];
